server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/product/**,/api/v1/category/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/api/v1/fallback/products

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/v1/cart/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: cartServiceCB
                    fallbackUri: forward:/api/v1/fallback/cart

            - id: eureka-server
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/
            
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payment/**

            - id: identity-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/user/**
                
resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      cartServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG     # Enable debug logs for troubleshooting

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always